# Generated by Django 2.2.9 on 2020-03-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMDB_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plot_summary', models.CharField(max_length=500)),
                ('directors', models.CharField(max_length=5000)),
                ('writers', models.CharField(max_length=5000)),
                ('stars', models.CharField(max_length=5000)),
                ('rating', models.FloatField(max_length=10)),
            ],
        ),
    ]
